"""Backward-compatible settings exports for the Streamlit application."""

from __future__ import annotations

from src.application.settings import (
    BATCH_ESTIMATED_MINUTES_PER_PAPER,
    BATCH_MAX_PAPER_WORKERS,
    DASHSCOPE_EMBEDDING_MODEL,
    DEFAULT_QDRANT_COLLECTION,
    EMBEDDING_API_KEY_ENV,
    EMBEDDING_DIM,
    EMBEDDING_MODEL,
    EMBEDDING_PROVIDER,
    EXTERNAL_CONTACT_EMAIL,
    EXTERNAL_HTTP_TIMEOUT_SECONDS,
    EXTERNAL_IMPORTS_DIR,
    EXTERNAL_MAX_PDF_MB,
    EXTERNAL_MONITOR_AUTO_RUN,
    LLM_MAX_CONCURRENT_REQUESTS,
    LLM_RATE_LIMIT_BACKOFF_SECONDS,
    LLM_RATE_LIMIT_RETRY_MAX,
    MINERU_CACHE_DIR,
    MINERU_FIGURE_VISION_MAX_WORKERS,
    OPENAI_EMBEDDING_BASE_URL,
    OPENAI_EMBEDDING_MODEL,
    PIPELINE_TIMEOUT_SECONDS,
    QWEN3_LOCAL_EMBEDDING_MAX_LENGTH,
    QWEN3_LOCAL_EMBEDDING_MODEL_PATH,
    QWEN3_LOCAL_EMBEDDING_QUERY_INSTRUCT,
    RERANK_DEFAULT_ENABLED,
    RESULTS_DIR,
    SAMPLE_DIR,
    SELECTIVE_RERANK_DEFAULT_ENABLED,
)
